name: bookings
services:
  postgres-data:
    image: postgres:17.5-alpine
    container_name: bookings_postgres-data
    environment:
      POSTGRES_DB: ${BK_POSTGRES_DB_NAME}
      POSTGRES_USER: ${BK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BK_POSTGRES_PASSWORD}
    ports:
      - '${BK_POSTGRES_EXTERNAL_PORT}:${BK_POSTGRES_INTERNAL_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${BK_POSTGRES_USER} -d ${BK_POSTGRES_DB_NAME}'
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookings_api
    env_file:
      - .env.production
    ports:
      - '${BK_API_PORT}:${BK_API_PORT}'
    depends_on:
      postgres-data:
        condition: service_healthy
    networks:
      - main
    restart: unless-stopped
    # Лимиты ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  api-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: bookings_api_migrate
    env_file:
      - .env.production
    depends_on:
      postgres-data:
        condition: service_healthy
    networks:
      - main
    command: sh -c "npm run prisma:db:push"
    restart: 'no'

volumes:
  postgres_data:

networks:
  main:
    driver: bridge
